/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import accesoDatos.HuespedData;
import entidades.Huesped;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author joadz
 */
public class huespedVista extends javax.swing.JInternalFrame {
    
    DefaultTableModel modelo = new DefaultTableModel();
    
    private final HuespedData hueData = new HuespedData();
    private Huesped huespedActual = null;
    
    public huespedVista() {
        initComponents();
        armarCabeceraTabla();
        armarTabla();
        
        jtTODOSLOSHUESPEDES.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int filaSeleccionada = jtTODOSLOSHUESPEDES.getSelectedRow();
                
                if (filaSeleccionada >= 0) {
                    int idHuesped = (int) jtTODOSLOSHUESPEDES.getValueAt(filaSeleccionada, 0);
                    int dni = (int) jtTODOSLOSHUESPEDES.getValueAt(filaSeleccionada, 1);
                    String nombre = (String) jtTODOSLOSHUESPEDES.getValueAt(filaSeleccionada, 2);
                    int celular = (int) jtTODOSLOSHUESPEDES.getValueAt(filaSeleccionada, 3);
                    boolean estado = (boolean) jtTODOSLOSHUESPEDES.getValueAt(filaSeleccionada, 4);
                    String domicilio = (String) jtTODOSLOSHUESPEDES.getValueAt(filaSeleccionada, 5);
                    String correo = (String) jtTODOSLOSHUESPEDES.getValueAt(filaSeleccionada, 6);

                    // Actualiza los campos de texto con los datos de la fila seleccionada
                    jTextIdHUESPED.setText(Integer.toString(idHuesped));
                    jTextNumeroDNI.setText(Integer.toString(dni));
                    jTextNOMBRE.setText(nombre);
                    jTextCELULARHUESPED.setText(Integer.toString(celular));
                    jRadioESTADOHUESPED.setSelected(estado);
                    jTextDOMICILIOHUESPED.setText(domicilio);
                    jTextCORREOHUESPED.setText(correo);
                }
            }
            
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelNOMBREHUESPED = new javax.swing.JPanel();
        JLAlumno = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jRadioESTADOHUESPED = new javax.swing.JRadioButton();
        jBLimpiarCampos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jBnuevoHuesped = new javax.swing.JButton();
        jBELIMINARHUESPED = new javax.swing.JButton();
        jBSalir3 = new javax.swing.JButton();
        jTextNumeroDNI = new javax.swing.JTextField();
        jTextDOMICILIOHUESPED = new javax.swing.JTextField();
        jTextNOMBRE = new javax.swing.JTextField();
        jButtonBuscarPorDni = new javax.swing.JButton();
        jButtonBuscarPorId = new javax.swing.JButton();
        jTextIdHUESPED = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextCORREOHUESPED = new javax.swing.JTextField();
        jTextCELULARHUESPED = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtTODOSLOSHUESPEDES = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jBActualizarHuesped = new javax.swing.JButton();

        jPanelNOMBREHUESPED.setBackground(new java.awt.Color(204, 255, 255));
        jPanelNOMBREHUESPED.setToolTipText("");

        JLAlumno.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JLAlumno.setForeground(new java.awt.Color(0, 153, 204));
        JLAlumno.setText("HUESPEDES");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Domicilio:");

        jRadioESTADOHUESPED.setBackground(new java.awt.Color(204, 255, 255));
        jRadioESTADOHUESPED.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioESTADOHUESPED.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioESTADOHUESPEDActionPerformed(evt);
            }
        });

        jBLimpiarCampos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBLimpiarCampos.setText("Limpiar campos");
        jBLimpiarCampos.setPreferredSize(new java.awt.Dimension(82, 25));
        jBLimpiarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarCamposActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Documento:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Estado del huesped:");

        jBnuevoHuesped.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBnuevoHuesped.setText("Nuevo huesped");
        jBnuevoHuesped.setPreferredSize(new java.awt.Dimension(82, 25));
        jBnuevoHuesped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnuevoHuespedActionPerformed(evt);
            }
        });

        jBELIMINARHUESPED.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBELIMINARHUESPED.setText("Eliminar huesped");
        jBELIMINARHUESPED.setPreferredSize(new java.awt.Dimension(82, 25));
        jBELIMINARHUESPED.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBELIMINARHUESPEDActionPerformed(evt);
            }
        });

        jBSalir3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBSalir3.setText("Salir");
        jBSalir3.setPreferredSize(new java.awt.Dimension(82, 25));
        jBSalir3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalir3ActionPerformed(evt);
            }
        });

        jButtonBuscarPorDni.setText("Buscar");
        jButtonBuscarPorDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarPorDniActionPerformed(evt);
            }
        });

        jButtonBuscarPorId.setText("Buscar");
        jButtonBuscarPorId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarPorIdActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Nº Huesped");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Correo Electronico:");

        jTextCELULARHUESPED.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCELULARHUESPEDActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Celular:");

        jtTODOSLOSHUESPEDES.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jtTODOSLOSHUESPEDES.setToolTipText("");
        jtTODOSLOSHUESPEDES.setCellSelectionEnabled(true);
        jScrollPane1.setViewportView(jtTODOSLOSHUESPEDES);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("***********");

        jBActualizarHuesped.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBActualizarHuesped.setText("Actualizar huesped");
        jBActualizarHuesped.setPreferredSize(new java.awt.Dimension(82, 25));
        jBActualizarHuesped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBActualizarHuespedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelNOMBREHUESPEDLayout = new javax.swing.GroupLayout(jPanelNOMBREHUESPED);
        jPanelNOMBREHUESPED.setLayout(jPanelNOMBREHUESPEDLayout);
        jPanelNOMBREHUESPEDLayout.setHorizontalGroup(
            jPanelNOMBREHUESPEDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNOMBREHUESPEDLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanelNOMBREHUESPEDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelNOMBREHUESPEDLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelNOMBREHUESPEDLayout.createSequentialGroup()
                        .addGroup(jPanelNOMBREHUESPEDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNOMBREHUESPEDLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(149, 149, 149)
                                .addComponent(jTextNumeroDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonBuscarPorDni))
                            .addGroup(jPanelNOMBREHUESPEDLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanelNOMBREHUESPEDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanelNOMBREHUESPEDLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextIdHUESPED, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonBuscarPorId))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNOMBREHUESPEDLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(376, 376, 376))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNOMBREHUESPEDLayout.createSequentialGroup()
                                .addGroup(jPanelNOMBREHUESPEDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanelNOMBREHUESPEDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextCORREOHUESPED, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextNOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextDOMICILIOHUESPED, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextCELULARHUESPED, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelNOMBREHUESPEDLayout.createSequentialGroup()
                                        .addComponent(jRadioESTADOHUESPED, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8)))
                                .addGap(83, 83, 83)))
                        .addContainerGap(54, Short.MAX_VALUE))))
            .addGroup(jPanelNOMBREHUESPEDLayout.createSequentialGroup()
                .addGroup(jPanelNOMBREHUESPEDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelNOMBREHUESPEDLayout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addGroup(jPanelNOMBREHUESPEDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jBELIMINARHUESPED, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBnuevoHuesped, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBLimpiarCampos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBSalir3, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBActualizarHuesped, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanelNOMBREHUESPEDLayout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(JLAlumno)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelNOMBREHUESPEDLayout.setVerticalGroup(
            jPanelNOMBREHUESPEDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNOMBREHUESPEDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanelNOMBREHUESPEDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextNumeroDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscarPorDni))
                .addGap(18, 18, 18)
                .addGroup(jPanelNOMBREHUESPEDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextIdHUESPED, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscarPorId))
                .addGap(18, 18, 18)
                .addGroup(jPanelNOMBREHUESPEDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextNOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanelNOMBREHUESPEDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextDOMICILIOHUESPED, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanelNOMBREHUESPEDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextCORREOHUESPED, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanelNOMBREHUESPEDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextCELULARHUESPED, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanelNOMBREHUESPEDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelNOMBREHUESPEDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jRadioESTADOHUESPED))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBnuevoHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBActualizarHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBELIMINARHUESPED, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBLimpiarCampos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBSalir3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelNOMBREHUESPED, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelNOMBREHUESPED, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioESTADOHUESPEDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioESTADOHUESPEDActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jRadioESTADOHUESPEDActionPerformed

    private void jBLimpiarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarCamposActionPerformed
        
        limpiarCampos();
        huespedActual = null;
    }//GEN-LAST:event_jBLimpiarCamposActionPerformed
    private void limpiarCampos() {
        jTextNumeroDNI.setText("");
        jTextNOMBRE.setText("");
        jTextIdHUESPED.setText("");
        jTextDOMICILIOHUESPED.setText("");
        jTextCELULARHUESPED.setText("");
        jTextCORREOHUESPED.setText("");
        jRadioESTADOHUESPED.setSelected(false);
        
        armarTabla();
    }
    

    private void jBnuevoHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnuevoHuespedActionPerformed
        
        try {
            String dniS = jTextNumeroDNI.getText();
            String nombre = jTextNOMBRE.getText();
            String domicilio = jTextDOMICILIOHUESPED.getText();
            String correo = jTextCORREOHUESPED.getText();
            Integer celular = Integer.parseInt(jTextCELULARHUESPED.getText());
            boolean estado = jRadioESTADOHUESPED.isSelected();
            int dni = Integer.parseInt(dniS);
            
            if (dni <= 0 || nombre.isEmpty() || domicilio.isEmpty() || correo.isEmpty() || celular <= 0) {
                JOptionPane.showMessageDialog(this, "Ingrese datos válidos en todos los campos obligatorios.");
                return;
            }
            
            if (huespedActual == null) {
                
                Huesped huespedExistente = hueData.obtenerHuespedPorDNIYID(dni); // Reemplaza "id" con el ID del huésped actual

                if (huespedExistente == null) {
                    huespedActual = new Huesped(nombre, dni, domicilio, correo, celular, estado);
                    hueData.agregarHuesped(huespedActual); // Agregar un nuevo huésped a la base de datos
                    JOptionPane.showMessageDialog(this, "Huesped guardado exitosamente.");
                } else {
                    JOptionPane.showMessageDialog(this, "El huésped ya existe en la base de datos.");
                }
                
            }
            
            limpiarCampos();
            huespedActual = null;
            
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "Ingrese un número válido en el campo DNI.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al guardar o modificar al huésped: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        

    }//GEN-LAST:event_jBnuevoHuespedActionPerformed

    private void jBELIMINARHUESPEDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBELIMINARHUESPEDActionPerformed
        if (huespedActual != null) {
            int confirmacion = JOptionPane.showConfirmDialog(this, "¿Seguro que desea eliminar este Huesped?", "Confirmar Eliminación", JOptionPane.YES_NO_OPTION);
            
            if (confirmacion == JOptionPane.YES_OPTION) {
                try {
                    // Intenta eliminar al alumno
                    hueData.eliminaHuesped(huespedActual.getIdHuesped());

                    // Limpia los campos y establece alumnoActual a null
                    limpiarCampos();
                    huespedActual = null;
                    
                    JOptionPane.showMessageDialog(this, "Huesped eliminado exitosamente.");
                } catch (Exception e) {
                    // Maneja las excepciones que puedan ocurrir durante la eliminación
                    JOptionPane.showMessageDialog(this, "Error al eliminar al huesped: ");
                }
            }
        } else {
            // Muestra un mensaje de advertencia si no se ha seleccionado un huesped
            JOptionPane.showMessageDialog(this, "No ha seleccionado ningún huesped para eliminar.");
        }

    }//GEN-LAST:event_jBELIMINARHUESPEDActionPerformed

    private void jBSalir3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalir3ActionPerformed
        dispose();
    }//GEN-LAST:event_jBSalir3ActionPerformed

    private void jButtonBuscarPorDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarPorDniActionPerformed
        
        try {
            
            String dniText = jTextNumeroDNI.getText();
            
            if (dniText.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Ingrese un número de DNI.");
                return;                
            }
            
            int dni = Integer.parseInt(dniText);
            
            huespedActual = hueData.buscarPorDni(dni);
            
            if (huespedActual != null) {
                
                jTextIdHUESPED.setText(Integer.toString(huespedActual.getIdHuesped()));
                jTextNOMBRE.setText(huespedActual.getNombre());
                jTextCELULARHUESPED.setText(Integer.toString(huespedActual.getCelular()));
                jTextCORREOHUESPED.setText(huespedActual.getCorreo());
                jTextDOMICILIOHUESPED.setText(huespedActual.getDomicilio());
                jRadioESTADOHUESPED.setSelected(huespedActual.isEstado());
            } else {
               
                JOptionPane.showMessageDialog(this, "No se encontró ningún huesped con ese DNI.");
            }
            
        } catch (NumberFormatException nf) {
            
            JOptionPane.showMessageDialog(this, "Ingrese un número válido en el campo de DNI.");
        }

    }//GEN-LAST:event_jButtonBuscarPorDniActionPerformed

    private void jButtonBuscarPorIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarPorIdActionPerformed
        try {
            int numHuesped = Integer.parseInt(jTextIdHUESPED.getText());
            huespedActual = hueData.buscarHuesped(numHuesped);
            
            if (huespedActual != null) {
                jTextNumeroDNI.setText(Integer.toString(huespedActual.getDni()));
                jTextIdHUESPED.setText(Integer.toString(huespedActual.getIdHuesped()));
                jTextNOMBRE.setText(huespedActual.getNombre());
                jTextCELULARHUESPED.setText(Integer.toString(huespedActual.getCelular()));
                jTextDOMICILIOHUESPED.setText(huespedActual.getDomicilio());
                jTextCORREOHUESPED.setText(huespedActual.getCorreo());
                jRadioESTADOHUESPED.setSelected(huespedActual.isEstado());
            } else {
                
                JOptionPane.showMessageDialog(this, "No se encontró ningún huesped con ese número.");
            }
        } catch (NumberFormatException nf) {
            
            JOptionPane.showMessageDialog(this, "Ingrese un número válido en el campo ID del Huesped.");
            
        }

    }//GEN-LAST:event_jButtonBuscarPorIdActionPerformed

    private void jTextCELULARHUESPEDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCELULARHUESPEDActionPerformed

    }//GEN-LAST:event_jTextCELULARHUESPEDActionPerformed

    private void jBActualizarHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBActualizarHuespedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBActualizarHuespedActionPerformed
    
    private void armarCabeceraTabla() {
        ArrayList<Object> filaCabecera = new ArrayList<>();
        
        filaCabecera.add("ID");
        filaCabecera.add("Dni");
        filaCabecera.add("Nombre");
        filaCabecera.add("Celular");
        filaCabecera.add("Estado");
        filaCabecera.add("Domicilio");
        filaCabecera.add("Correo");
        
        for (Object columnHeader : filaCabecera) {
            modelo.addColumn(columnHeader);
        }
        
    }
    
    private void armarTabla() {
        ArrayList<Huesped> listaHuespedes = hueData.obtenerTodosLosHuespedes();
        modelo.setRowCount(0);
        
        for (Huesped huesped : listaHuespedes) {
            Object[] fila = {
                huesped.getIdHuesped(),
                huesped.getDni(),
                huesped.getNombre(),
                huesped.getCelular(),
                huesped.isEstado(),
                huesped.getDomicilio(),
                huesped.getCorreo()
            };
            
            modelo.addRow(fila);
        }
        
        jtTODOSLOSHUESPEDES.setModel(modelo);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLAlumno;
    private javax.swing.JButton jBActualizarHuesped;
    private javax.swing.JButton jBELIMINARHUESPED;
    private javax.swing.JButton jBLimpiarCampos;
    private javax.swing.JButton jBSalir3;
    private javax.swing.JButton jBnuevoHuesped;
    private javax.swing.JButton jButtonBuscarPorDni;
    private javax.swing.JButton jButtonBuscarPorId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanelNOMBREHUESPED;
    private javax.swing.JRadioButton jRadioESTADOHUESPED;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextCELULARHUESPED;
    private javax.swing.JTextField jTextCORREOHUESPED;
    private javax.swing.JTextField jTextDOMICILIOHUESPED;
    private javax.swing.JTextField jTextIdHUESPED;
    private javax.swing.JTextField jTextNOMBRE;
    private javax.swing.JTextField jTextNumeroDNI;
    private javax.swing.JTable jtTODOSLOSHUESPEDES;
    // End of variables declaration//GEN-END:variables
}
